#spring configuration
spring:
   application:
      name: mysite06

   devtools:
      restart:
         enabled: true
      livereload:
         enabled: true

   #whether bean-definition-overriding
   main:
      allow-bean-definition-overriding: true

   #aop
   aop:
      auto: true
      proxy-target-class: true

   #mvc
   #mvc:
      #view:
         #prefix: /WEB-INF/views/
         #suffix: .jsp
   
   #message resource(i18n)
   messages:
      basename: messages/message
      encoding: utf-8

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.18:3306/webdb
      username: webdb
      password: webdb
      hikari: 
         minimum-idle: 10
         maximum-pool-size: 20

#mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

#server configuration
server:
   port: 8080
   servlet:
      context-path: /mysite06